name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure environment
        env:
          DOCKER_TAG: ${{ github.ref }}
        run: echo ${DOCKER_TAG}
      - name: Test environment
        run: echo ${DOCKER_TAG}
#      - name: Build the Docker image
#        run: docker build . -f Dockerfile -t maticinsurance/gocd-agent-with-dcind:latest
#      - name: Tag docker image
#        run: docker tag maticinsurance/gocd-agent-with-dcind:latest maticinsurance/gocd-agent-with-dcind:${{ github.ref }}
#      - name: Login to Docker
#        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#      - name: Push docker image
#        run: |
#          docker push maticinsurance/gocd-agent-with-dcind:latest
#          docker push maticinsurance/gocd-agent-with-dcind:${{ github.ref }}
